### ISSUE TITLE
EPG URL

### ISSUE THREAD

**Issue by onestix** [parker1992/iptv-proxy#6]
Hi @parker1992 - following our conversation here https://github.com/pierre-emmanuelJ/iptv-proxy/issues/120 it is understood that your repo does not support xtream and that's fine since I have access to an m3u- and an epg file. I am still however having trouble understanding how you are proxying epg data if no epg file is defined. Would you mind clarifying where/how I can define the EPG url using your repo?

Thanks

**Comment by onestix** [comment]
Nevermind, just read your repo description and it seems that I need to include the URL manually in my m3u. Would it be possible to have this as an env variable?

Cheers

**Comment by parker1992** [comment]
The m3u should have a line such as '#EXTM3U url-tvg="http://url-to-epg.com/epg"' which will have the URLs prefixed to go through the proxy.

If you have a separate EPG that's not in the m3u and want to provide that separately, that's in coach's PR which I'll review tonight.

Also for URLs within the EPG which I'm not sure what those are needed for, coach's PR addresses those too.

**Comment by onestix** [comment]
Perfect, it all makes sense now :)

Thanks for your help on this. Cheers

**Comment by parker1992** [comment]
@coach1988 

Released this as 0.2.0
